subjects:
  - id: "math"
    name: "Mathématiques"
    description: "Utiliser les langages scientifiques"
    ai_agent: "OpenAI"
  - id: "physics"
    name: "Physique/Chimie"
    description: "Systèmes naturels et techniques"
    ai_agent: "OpenAI"
  - id: "info"
    name: "Informatique"
    description: "Méthodes et outils pour apprendre (EMI)"
    ai_agent: "OpenAI"
  - id: "english"
    name: "Anglais"
    description: "Utiliser une langue étrangère"
    ai_agent: "OpenAI"
